[project]
name = "dataryx-flet"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
authors = [
    { name = "Dataryx Team" }
]
dependencies = [
    "flet>=0.85.1",
    "polars>=1.8.2",
    "pyarrow>=18.0.0",
    "sqlalchemy>=2.0.27",
    "pydantic>=2.9.2",
    "httpx>=0.28.1",
    "python-jose[cryptography]>=3.3.0",
    "bcrypt>=3.1.7",
    "apscheduler>=3.10.4",
    "aiofiles>=24.1.0",
    "python-dotenv>=1.0.0",
    "cryptography>=45.0.5",
    "pl-fuzzy-frame-match>=0.6.0",
    "polars-expr-transformer>=0.5.4",
    "polars-grouper>=0.4.0",
    "polars-ds>=0.11.2",
    "fastexcel>=0.20.2",
    "xlsxwriter>=3.2.9",
    "connectorx>=0.4.5",
    "polars-simed>=0.4.0",
    "deltalake>=1.6.0",
    "pyiceberg>=0.11.1",
    "boto3>=1.43.16",
    "s3fs>=0.4.2",
    "pyyaml>=6.0.3",
    "methodtools>=0.4.7",
    "faker>=40.19.1",
    "openpyxl>=3.1.5",
    "polars-distance>=0.4.3",
    "loky>=3.5.6",
    "pytz>=2026.2",
]

[dependency-groups]
dev = [
    "flet-cli>=0.85.1",
    "flet-desktop>=0.85.1",
    "flet-web>=0.85.1",
    "pytest>=8.4.1",
    "pytest-cov>=6.0",
    "pyinstaller>=6.11.0"
]

[tool.flet]
org = "com.mycompany"
product = "dataryx-flet"
company = "Flet"
copyright = "Copyright (C) 2023-2026 by Flet"

[tool.flet.app]
path = "src"
